# Generated by Django 4.2.6 on 2023-10-25 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_post_rate_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='rate',
        ),
        migrations.RemoveField(
            model_name='post',
            name='rate_count',
        ),
        migrations.AddField(
            model_name='profile',
            name='rate',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='rate_count',
            field=models.IntegerField(default=0),
        ),
    ]
