# Generated by Django 4.2.6 on 2023-10-25 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_remove_post_rate_remove_post_rate_count_profile_rate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='rate',
            field=models.FloatField(default=0),
        ),
    ]
